server.port=${PORT:8080}
server.address=0.0.0.0
server.forward-headers-strategy=framework
server.servlet.session.cookie.secure=true
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
