create table generation (
 id bigint generated by default as identity primary key,
 owner varchar(255) not null,
 name varchar(100) not null,
 birth_year integer not null,
 unique(owner, name)
);
create table player (
 id bigint generated by default as identity primary key,
 generation_id bigint not null references generation(id),
 name varchar(150) not null,
 shirt_number integer not null,
 joined_on date not null,
 unique(generation_id, shirt_number)
);
create table training_session (
 id bigint generated by default as identity primary key,
 generation_id bigint not null references generation(id),
 training_date date not null,
 start_time time not null,
 end_time time not null,
 location varchar(150) not null,
 notes varchar(500) not null,
 cancelled boolean not null default false,
 recorded boolean not null default false,
 revision bigint not null default 0,
 unique(generation_id, training_date, start_time)
);
create table player_attendance (
 id bigint generated by default as identity primary key,
 session_id bigint not null references training_session(id),
 player_id bigint not null references player(id),
 present boolean not null,
 unique(session_id, player_id)
);
create index idx_generation_owner on generation(owner);
create index idx_player_generation on player(generation_id);
create index idx_training_generation_date on training_session(generation_id,training_date);
create index idx_player_attendance_player on player_attendance(player_id);
